name: jmallspgh
favicon: null
layout_spectrum: 0.25668
typography_spectrum: 0.39006
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#e5b53c'
    - '#ffffff'
    - '#000000'
    - '#554315'
    - '#af892d'
  brandStrength: 0.767255138605833
  lightness: 0.6436275411397219
  saturation: 0.6025588386692107
  rhythmicContrast: 0.23147807735949755
purpose: []
